name: CI

on:
  push:
  # Publish `master` as Docker `latest` image.
    branches:
      - master

  # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run a one-line script
      run: echo Hello, world!
      
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: Only on tag
      run: echo $GITHUB_EVENT_NAME
